'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'

const modes=[
 ['week','▦','Organizar minha semana','Monte um plano semanal realista, distribuindo prioridades, revisões e preparação para provas.'],
 ['today','◎','O que estudar hoje?','Defina o que devo estudar hoje, em qual ordem e por quanto tempo.'],
 ['exam','⚑','Plano até a próxima prova','Crie um plano progressivo até minha próxima avaliação, priorizando lacunas e conteúdos críticos.'],
 ['reviews','↻','Organizar revisões','Organize minhas revisões espaçadas considerando domínio, atraso e proximidade das avaliações.'],
 ['performance','↗','Analisar desempenho','Analise meus dados de estudo e identifique prioridades, gargalos e próximos passos.'],
 ['risk','!','Conteúdos em risco','Identifique os conteúdos com maior risco acadêmico e proponha uma ordem de ataque.']
]

function clean(items){return items?.length?items:[]}
export default function PromptCenter(){
 const [context,setContext]=useState({tasks:[],contents:[],assessments:[],recentStudy:[]});const [selected,setSelected]=useState('week');const [copied,setCopied]=useState(false);const [loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const [t,c,a,s]=await Promise.all([supabase.from('tasks').select('name,subject,due_date,done'),supabase.from('contents').select('name,subject,mastery,next_review'),supabase.from('assessments').select('name,subject,assessment_date'),supabase.from('study_sessions').select('subject,topic,minutes,questions,correct,studied_at').order('studied_at',{ascending:false}).limit(20)]);setContext({tasks:clean(t.data),contents:clean(c.data),assessments:clean(a.data),recentStudy:clean(s.data)});setLoading(false)})()},[])
 const mode=modes.find(x=>x[0]===selected)
 const prompt=useMemo(()=>{const open=context.tasks.filter(t=>!t.done);return `Você será meu orientador de organização acadêmica. Eu uso o GTD Acadêmico para registrar tarefas, avaliações, conteúdos, revisões e sessões de estudo.\n\nOBJETIVO\n${mode[3]}\n\nMEUS DADOS ATUAIS\nTarefas abertas:\n${open.length?open.map(t=>`- ${t.name} | ${t.subject||'Geral'} | prazo: ${t.due_date||'sem prazo'}`).join('\n'):'- Nenhuma tarefa aberta cadastrada.'}\n\nAvaliações:\n${context.assessments.length?context.assessments.map(a=>`- ${a.name} | ${a.subject||'Geral'} | data: ${a.assessment_date||'sem data'}`).join('\n'):'- Nenhuma avaliação cadastrada.'}\n\nConteúdos e revisões:\n${context.contents.length?context.contents.map(c=>`- ${c.name} | ${c.subject||'Geral'} | domínio: ${c.mastery||'não informado'} | próxima revisão: ${c.next_review||'não definida'}`).join('\n'):'- Nenhum conteúdo cadastrado.'}\n\nSessões recentes:\n${context.recentStudy.length?context.recentStudy.map(s=>`- ${s.subject||'Geral'} / ${s.topic||'estudo'} | ${s.minutes||0} min | questões: ${s.questions||0} | acertos: ${s.correct||0}`).join('\n'):'- Nenhuma sessão recente cadastrada.'}\n\nINSTRUÇÕES\n1. Use os dados acima como fonte principal e não invente compromissos.\n2. Priorize provas próximas, tarefas atrasadas, conteúdos fracos e revisões pendentes.\n3. Se faltar informação importante, faça poucas perguntas objetivas antes de fechar o plano.\n4. Entregue um plano prático, com prioridades claras e carga realista.\n5. Ao final, crie uma seção chamada “Atualizações para o GTD Acadêmico” com uma lista objetiva do que devo cadastrar ou alterar no app.`},[context,mode])
 async function copy(){await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),1800)}
 return <main className="standalonePage"><div className="standaloneTop"><a href="/">← Voltar ao painel</a><span>GTD ACADÊMICO</span></div><section className="standaloneHero"><div className="standaloneEyebrow">CENTRAL DE PROMPTS</div><h1>Seu GTD + seu ChatGPT.</h1><p>Escolha um objetivo e o GTD Acadêmico prepara automaticamente um prompt com seus próprios dados. Você usa a sua conta do ChatGPT — sem consumir créditos de API do site.</p></section><div className="promptLayout"><section><div className="promptChoices">{modes.map(([id,icon,title])=><button key={id} className={selected===id?'selected':''} onClick={()=>setSelected(id)}><i>{icon}</i><span>{title}</span></button>)}</div><article className="promptCard"><div className="promptCardHead"><div><span>PROMPT PERSONALIZADO</span><h2>{mode[2]}</h2></div><span className="contextBadge">{context.tasks.length+context.contents.length+context.assessments.length} itens no contexto</span></div>{loading?<div className="empty">Preparando seus dados…</div>:<textarea readOnly value={prompt}/>}<div className="promptActions"><button onClick={copy}>{copied?'✓ Prompt copiado':'Copiar prompt'}</button><a href="https://chatgpt.com/" target="_blank" rel="noreferrer">Abrir meu ChatGPT ↗</a></div></article></section><aside className="howCard"><span>COMO USAR</span><h3>Três passos. Zero custo de API para o GTD.</h3><ol><li><b>1</b><div>Escolha o que você quer organizar.</div></li><li><b>2</b><div>Copie o prompt gerado com seus dados acadêmicos.</div></li><li><b>3</b><div>Abra sua conta do ChatGPT, cole e continue a conversa normalmente.</div></li></ol><div className="privacyNote">O prompt é montado no seu navegador a partir da sua conta. Só é enviado ao ChatGPT quando você decide copiar e colar.</div></aside></div></main>
}
