'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'

const prompts=['Organize minha semana','O que devo estudar hoje?','Monte um plano até minha próxima prova','Quais conteúdos estão em maior risco?','Organize minhas revisões','Analise meu desempenho e sugira prioridades']

export default function AssistantPage(){
 const [message,setMessage]=useState('');const [answer,setAnswer]=useState('');const [busy,setBusy]=useState(false);const [context,setContext]=useState({})
 useEffect(()=>{(async()=>{const [t,c,a,s]=await Promise.all([supabase.from('tasks').select('name,subject,due_date,done'),supabase.from('contents').select('name,subject,mastery,next_review'),supabase.from('assessments').select('name,subject,assessment_date'),supabase.from('study_sessions').select('subject,topic,minutes,questions,correct,studied_at').order('studied_at',{ascending:false}).limit(30)]);setContext({tasks:t.data||[],contents:c.data||[],assessments:a.data||[],recentStudy:s.data||[]})})()},[])
 async function ask(text=message){if(!text.trim())return;setBusy(true);setAnswer('');const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,context})});const d=await r.json();setAnswer(d.text||d.error||'Não foi possível responder.');setBusy(false)}
 return <main style={{maxWidth:1000,margin:'0 auto',padding:'32px 20px',fontFamily:'Inter,system-ui'}}><a href="/" style={{textDecoration:'none'}}>← Voltar ao GTD Acadêmico</a><h1>✨ Assistente Acadêmico</h1><p>Central de Prompts inteligente. A IA recebe o contexto acadêmico da sua conta para ajudar a planejar estudos. Nesta primeira versão, ela sugere mudanças antes de qualquer alteração no sistema.</p><div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'24px 0'}}>{prompts.map(p=><button key={p} onClick={()=>{setMessage(p);ask(p)}} style={{padding:'10px 12px',border:0,borderRadius:10,cursor:'pointer'}}>{p}</button>)}</div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ex.: Tenho prova em 10 dias e estou atrasado. Reorganize meu estudo." style={{width:'100%',minHeight:120,padding:14,borderRadius:12,border:'1px solid #dfe3ea'}}/><button onClick={()=>ask()} disabled={busy} style={{marginTop:12,padding:'12px 18px',border:0,borderRadius:10,cursor:'pointer'}}>{busy?'Analisando…':'Pedir ajuda à IA'}</button>{answer&&<section style={{whiteSpace:'pre-wrap',marginTop:24,padding:20,border:'1px solid #e5e8ee',borderRadius:16,background:'#fff'}}>{answer}</section>}<p style={{marginTop:24,fontSize:12,color:'#667085'}}>Próxima evolução: mostrar ações propostas e permitir confirmar a criação/reorganização de tarefas, revisões e sessões de estudo.</p></main>
}
