'use client'
import {useEffect,useState} from 'react'
import {supabase} from '../../lib/supabase'

const prompts=['Organize minha semana','O que devo estudar hoje?','Monte um plano até minha próxima prova','Quais conteúdos estão em maior risco?','Organize minhas revisões','Analise meu desempenho e sugira prioridades']

export default function AssistantPage(){
 const [message,setMessage]=useState('');const [answer,setAnswer]=useState('');const [busy,setBusy]=useState(false);const [context,setContext]=useState({})
 useEffect(()=>{(async()=>{const [t,c,a,s]=await Promise.all([supabase.from('tasks').select('name,subject,due_date,done'),supabase.from('contents').select('name,subject,mastery,next_review'),supabase.from('assessments').select('name,subject,assessment_date'),supabase.from('study_sessions').select('subject,topic,minutes,questions,correct,studied_at').order('studied_at',{ascending:false}).limit(30)]);setContext({tasks:t.data||[],contents:c.data||[],assessments:a.data||[],recentStudy:s.data||[]})})()},[])
 async function ask(text=message){if(!text.trim())return;setBusy(true);setAnswer('');try{const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,context})});const d=await r.json();setAnswer(d.text||d.error||'Não foi possível responder.')}catch{setAnswer('Não foi possível conectar ao assistente agora.')}setBusy(false)}
 return <main className="standalone"><div className="standaloneTop"><a href="/">← Voltar ao painel</a><a href="/semana">▦ Semana Acadêmica</a></div><section className="standaloneHero"><span>INTELIGÊNCIA ACADÊMICA</span><h1>✦ Assistente Acadêmico</h1><p>Converse com o seu GTD. A IA recebe o contexto da sua conta para ajudar a planejar estudos, identificar riscos e organizar prioridades sem alterar seus dados sem confirmação.</p></section><section className="assistantBox"><div className="pageIntro"><span>CENTRAL DE PROMPTS</span><h2>Como posso organizar seus estudos?</h2><p>Escolha um atalho ou escreva livremente o que você precisa.</p></div><div className="promptChips">{prompts.map(p=><button key={p} onClick={()=>{setMessage(p);ask(p)}}>{p}</button>)}</div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ex.: Tenho prova em 10 dias, estou atrasado em três conteúdos e só tenho 2 horas por dia. Reorganize meu plano."/><button onClick={()=>ask()} disabled={busy} style={{marginTop:12}}>{busy?'Analisando seu contexto…':'✦ Pedir ajuda à IA'}</button>{answer&&<section className="assistantAnswer">{answer}</section>}</section><p style={{marginTop:18,fontSize:11,color:'#7b8493'}}>A IA desta versão analisa e sugere. A próxima evolução permitirá revisar e confirmar ações antes de criar tarefas, revisões e sessões automaticamente.</p></main>
}
