'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'

function fmt(value){if(!value)return'—';return new Date(value).toLocaleString('pt-BR')}
function online(lastSeen){if(!lastSeen)return false;return Date.now()-new Date(lastSeen).getTime()<15*60*1000}

export default function AdminPage(){
 const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 async function load(){setLoading(true);setError('');const{data,error}=await supabase.rpc('get_admin_dashboard');if(error){setError('Acesso restrito ou não foi possível carregar os dados.');setRows([])}else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const stats=useMemo(()=>({total:rows.length,online:rows.filter(r=>online(r.last_seen_at)).length,recent:rows.filter(r=>r.last_sign_in_at&&Date.now()-new Date(r.last_sign_in_at).getTime()<7*86400000).length,active:rows.filter(r=>(Number(r.tasks_count)||0)+(Number(r.contents_count)||0)+(Number(r.assessments_count)||0)+(Number(r.study_sessions_count)||0)>0).length}),[rows])
 return <main style={{maxWidth:1280,margin:'0 auto',padding:'34px 22px 60px',fontFamily:'Inter,system-ui',color:'#111827'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,marginBottom:20}}><a href="/" style={{textDecoration:'none',fontSize:12}}>← Voltar ao GTD Acadêmico</a><button onClick={load} style={{border:0,borderRadius:11,padding:'10px 14px',fontWeight:800,cursor:'pointer'}}>Atualizar dados</button></div>
  <section style={{padding:28,borderRadius:22,background:'linear-gradient(135deg,#101827,#202c46)',color:'#fff',marginBottom:16}}><div style={{fontSize:10,letterSpacing:'.16em',fontWeight:900,color:'#aebcff'}}>PAINEL ADMIN</div><h1 style={{fontSize:30,margin:'8px 0'}}>Usuários e atividade</h1><p style={{color:'#c8d1df',maxWidth:760,lineHeight:1.6}}>Acompanhe cadastros, último login, presença recente e uso dos principais módulos do GTD Acadêmico.</p></section>
  {error&&<div style={{padding:14,border:'1px solid #fecaca',background:'#fff1f2',borderRadius:12,color:'#9f1239',marginBottom:14}}>{error}</div>}
  <section style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:12,marginBottom:16}}>{[['Usuários',stats.total],['Online agora',stats.online],['Login nos últimos 7 dias',stats.recent],['Já usaram o app',stats.active]].map(([label,value])=><article key={label} style={{background:'#fff',border:'1px solid #e5e7eb',borderRadius:16,padding:18}}><span style={{fontSize:10,color:'#6b7280',fontWeight:800}}>{label}</span><b style={{display:'block',fontSize:30,marginTop:8}}>{value}</b></article>)}</section>
  <section style={{background:'#fff',border:'1px solid #e5e7eb',borderRadius:18,overflow:'hidden'}}><div style={{padding:18,borderBottom:'1px solid #eef0f3'}}><b>Contas cadastradas</b><div style={{fontSize:12,color:'#6b7280',marginTop:4}}>“Online” considera atividade registrada nos últimos 15 minutos.</div></div>{loading?<div style={{padding:28,color:'#6b7280'}}>Carregando…</div>:rows.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr>{['Usuário','Status','Cadastro','Último login','Última atividade','Uso do app'].map(h=><th key={h} style={{textAlign:'left',padding:'12px 14px',borderBottom:'1px solid #eef0f3',color:'#6b7280'}}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.user_id}><td style={{padding:'13px 14px',borderBottom:'1px solid #f1f3f5'}}><b>{r.full_name||'Sem nome'}</b><div style={{color:'#6b7280',marginTop:3}}>{r.email}</div></td><td style={{padding:'13px 14px',borderBottom:'1px solid #f1f3f5'}}><span style={{padding:'5px 8px',borderRadius:999,background:online(r.last_seen_at)?'#e8f7ee':'#f3f4f6',color:online(r.last_seen_at)?'#247a45':'#6b7280',fontWeight:800}}>{online(r.last_seen_at)?'Online':'Offline'}</span></td><td style={{padding:'13px 14px',borderBottom:'1px solid #f1f3f5'}}>{fmt(r.created_at)}</td><td style={{padding:'13px 14px',borderBottom:'1px solid #f1f3f5'}}>{fmt(r.last_sign_in_at)}</td><td style={{padding:'13px 14px',borderBottom:'1px solid #f1f3f5'}}>{fmt(r.last_seen_at)}</td><td style={{padding:'13px 14px',borderBottom:'1px solid #f1f3f5'}}>T {r.tasks_count||0} · C {r.contents_count||0} · A {r.assessments_count||0} · S {r.study_sessions_count||0}</td></tr>)}</tbody></table></div>:<div style={{padding:28,color:'#6b7280'}}>Nenhum usuário encontrado.</div>}</section>
  <p style={{fontSize:11,color:'#8791a0',marginTop:14}}>Este painel é protegido no banco: apenas contas cadastradas como administradoras conseguem consultar os dados.</p>
 </main>
}
