'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'

export default function WeekPage(){
 const [items,setItems]=useState([]);const [form,setForm]=useState({title:'',item_type:'Estudo',subject:'',starts_at:'',notes:''})
 const load=()=>supabase.from('academic_week_items').select('*').order('starts_at').then(({data})=>setItems(data||[]))
 useEffect(()=>{load()},[])
 const range=useMemo(()=>{const d=new Date();const day=(d.getDay()+6)%7;const start=new Date(d);start.setDate(d.getDate()-day);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+7);return {start,end}},[])
 const week=items.filter(i=>{if(!i.starts_at)return true;const d=new Date(i.starts_at);return d>=range.start&&d<range.end})
 async function add(e){e.preventDefault();const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from('academic_week_items').insert({user_id:user.id,title:form.title,item_type:form.item_type,subject:form.subject||null,starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,notes:form.notes||null});setForm({title:'',item_type:'Estudo',subject:'',starts_at:'',notes:''});load()}
 async function remove(id){await supabase.from('academic_week_items').delete().eq('id',id);load()}
 return <main className="standalone"><div className="standaloneTop"><a href="/">← Voltar ao painel</a><a href="/assistente">✦ Assistente IA</a></div><section className="standaloneHero"><span>PLANEJAMENTO SEMANAL</span><h1>▦ Semana Acadêmica</h1><p>Transforme a semana em uma visão operacional: estudo, aulas, provas, revisões e compromissos no mesmo lugar.</p></section><div className="weekGrid"><form className="weekForm" onSubmit={add}><div className="pageIntro"><span>NOVO ITEM</span><h2>Adicionar à semana</h2><p>Registre o que precisa ocupar espaço real na sua agenda.</p></div><input required placeholder="Atividade" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.item_type} onChange={e=>setForm({...form,item_type:e.target.value})}><option>Estudo</option><option>Aula</option><option>Prova</option><option>Revisão</option><option>Compromisso</option></select><input placeholder="Disciplina" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/><input placeholder="Observações" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button>＋ Adicionar à semana</button><a href="/assistente" style={{textDecoration:'none',fontSize:11,color:'#5b63d7',fontWeight:800,textAlign:'center'}}>✦ Pedir para a IA organizar esta semana</a></form><section className="weekList"><div className="pageIntro"><span>SEMANA ATUAL</span><h2>Seu plano operacional</h2><p>{range.start.toLocaleDateString('pt-BR')} — {new Date(range.end.getTime()-86400000).toLocaleDateString('pt-BR')}</p></div>{week.length?week.map(i=><article className="weekItem" key={i.id}><div><b>{i.title}</b><div className="weekMeta">{i.item_type} · {i.subject||'Geral'}{i.starts_at?` · ${new Date(i.starts_at).toLocaleString('pt-BR')}`:''}</div>{i.notes&&<div style={{fontSize:12,marginTop:6,lineHeight:1.5}}>{i.notes}</div>}</div><button onClick={()=>remove(i.id)}>Excluir</button></article>):<div className="empty">Nenhum item cadastrado nesta semana.<br/><small>Adicione manualmente ou peça ajuda ao Assistente IA.</small></div>}</section></div></main>
}
