'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../../lib/supabase'

export default function WeekPage(){
 const [items,setItems]=useState([]);const [form,setForm]=useState({title:'',item_type:'Estudo',subject:'',starts_at:'',notes:''})
 const load=()=>supabase.from('academic_week_items').select('*').order('starts_at').then(({data})=>setItems(data||[]))
 useEffect(()=>{load()},[])
 const range=useMemo(()=>{const d=new Date();const day=(d.getDay()+6)%7;const start=new Date(d);start.setDate(d.getDate()-day);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+7);return {start,end}},[])
 const week=items.filter(i=>{if(!i.starts_at)return true;const d=new Date(i.starts_at);return d>=range.start&&d<range.end})
 async function add(e){e.preventDefault();const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from('academic_week_items').insert({user_id:user.id,title:form.title,item_type:form.item_type,subject:form.subject||null,starts_at:form.starts_at?new Date(form.starts_at).toISOString():null,notes:form.notes||null});setForm({title:'',item_type:'Estudo',subject:'',starts_at:'',notes:''});load()}
 async function remove(id){await supabase.from('academic_week_items').delete().eq('id',id);load()}
 return <main style={{maxWidth:1050,margin:'0 auto',padding:'32px 20px',fontFamily:'Inter,system-ui'}}><a href="/" style={{textDecoration:'none'}}>← Voltar ao GTD Acadêmico</a><h1>🗓 Semana Acadêmica</h1><p>Uma visão operacional da semana para reunir estudo, aulas, provas, revisões e compromissos.</p><form onSubmit={add} style={{display:'grid',gap:10,padding:20,border:'1px solid #e5e8ee',borderRadius:16,background:'#fff',margin:'22px 0'}}><input required placeholder="Atividade" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.item_type} onChange={e=>setForm({...form,item_type:e.target.value})}><option>Estudo</option><option>Aula</option><option>Prova</option><option>Revisão</option><option>Compromisso</option></select><input placeholder="Disciplina" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/><input placeholder="Observações" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button>Adicionar à semana</button></form>{week.length?week.map(i=><article key={i.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:'14px 0',borderBottom:'1px solid #edf0f4'}}><div><b>{i.title}</b><div style={{fontSize:12,color:'#667085',marginTop:4}}>{i.item_type} · {i.subject||'Geral'}{i.starts_at?` · ${new Date(i.starts_at).toLocaleString('pt-BR')}`:''}</div>{i.notes&&<div style={{fontSize:12,marginTop:5}}>{i.notes}</div>}</div><button onClick={()=>remove(i.id)}>Excluir</button></article>):<p>Nenhum item cadastrado nesta semana.</p>}<p style={{marginTop:28}}><a href="/assistente">✨ Pedir para a IA organizar minha semana →</a></p></main>
}
